export interface TrainedAiSummaryModel {
  version: string;
  featureOrder: string[];
  featureStats: Record<string, { mean: number; std: number }>;
  levelCentroids: Record<"beginner" | "intermediate" | "advanced", number[]>;
  adviceCentroids: Record<string, number[]>;
  adviceThresholds: Record<string, number>;
}

// Auto-generated by ml/train_ai_summary_model.py
export const trainedAiSummaryModel: TrainedAiSummaryModel = {"version": "trained-20260423-084353", "featureOrder": ["overall_accuracy", "mcq_accuracy", "subjective_score", "consistency", "attempted_ratio", "avg_time_spent", "avg_difficulty"], "featureStats": {"overall_accuracy": {"mean": 0.61317, "std": 0.20638960996135441}, "mcq_accuracy": {"mean": 0.651113, "std": 0.20076740579835164}, "subjective_score": {"mean": 0.5561900000000001, "std": 0.24027014775040198}, "consistency": {"mean": 0.614056, "std": 0.19442311813156377}, "attempted_ratio": {"mean": 0.798744, "std": 0.18968680097465926}, "avg_time_spent": {"mean": 1.0, "std": 1.0}, "avg_difficulty": {"mean": 1.0, "std": 1.0}}, "levelCentroids": {"beginner": [0, 0, 0, 0, 0, 0, 0], "intermediate": [0, 0, 0, 0, 0, 0, 0], "advanced": [0, 0, 0, 0, 0, 0, 0]}, "adviceCentroids": {"revise_fundamentals": [0, 0, 0, 0, 0, 0, 0], "practice_mcq": [0, 0, 0, 0, 0, 0, 0], "practice_subjective": [0, 0, 0, 0, 0, 0, 0], "improve_consistency": [0, 0, 0, 0, 0, 0, 0], "level_up_challenge": [0, 0, 0, 0, 0, 0, 0], "improve_speed": [0, 0, 0, 0, 0, 0, 0], "read_carefully": [0, 0, 0, 0, 0, 0, 0]}, "adviceThresholds": {"revise_fundamentals": 1.4, "practice_mcq": 1.4, "practice_subjective": 1.4, "improve_consistency": 1.4, "level_up_challenge": 1.4, "improve_speed": 1.4, "read_carefully": 1.4}, "rowsTrained": 10000}
